name: Package JS build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        haxe: [4.3.3]
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      # Checkout & install haxe
      - uses: actions/checkout@v2

      - name: Restore cached haxe installation
        id: restore-haxe
        uses: actions/cache/restore@v4
        with:
          path: |
            /opt/hostedtoolcache/haxe
          key: ${{ runner.os }}-${{ hashFiles('setup.hxml') }}
      
      - uses: krdlab/setup-haxe@v1
        # if: steps.restore-haxe.outputs.cache-hit != 'true'
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version

      # Install libs if cache not found
      - run: haxe setup.hxml
        if: steps.restore-haxe.outputs.cache-hit != 'true'

      - run: haxelib list

      - name: Save haxe cache
        id: save-haxe
        uses: actions/cache/save@v4
        with:
          path: |
            /opt/hostedtoolcache/haxe
          key: ${{ steps.restore-haxe.outputs.cache-primary-key }}

      # Run build
      # - run: haxe build.js.hxml

      - name: Package project
        run: haxelib run redistHelper build.js.hxml -o redist -p GameBase
      - run: tree
      - name: Compress
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./redist
          files: |
            ./js/*
          outPath: github_pages.tar.gz
      
      - name: Upload GH pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github_pages
          path: ./redist/github_pages.tar.gz
        

