name: Package builds

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    permissions: 
      id-token: write
    steps:
      # Checkout & install haxe
      - uses: actions/checkout@v2

      - name: Restore cached haxe installation
        id: restore-haxe
        uses: actions/cache/restore@v4
        with:
          path: |
            /opt/hostedtoolcache/haxe
          key: ${{ runner.os }}-${{ hashFiles('setup.hxml') }}
      
      - uses: krdlab/setup-haxe@v1
        # if: steps.restore-haxe.outputs.cache-hit != 'true'
        with:
          haxe-version: 4.3.3
      - run: haxe -version

      # Install libs if cache not found
      - run: haxe setup.hxml
        if: steps.restore-haxe.outputs.cache-hit != 'true'

      - run: haxelib list

      - name: Save haxe cache
        id: save-haxe
        uses: actions/cache/save@v4
        with:
          path: |
            /opt/hostedtoolcache/haxe
          key: ${{ steps.restore-haxe.outputs.cache-primary-key }}

      # Run build
      # - run: haxe build.js.hxml

      - uses: cedx/setup-hashlink@v6
        with:
          version: latest
      - run: which hl
      - name: Package project
        run: haxelib run redistHelper build.js.hxml build.directx.hxml build.opengl.hxml -o redist -p GameBase
        
      - name: Upload build files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: redist/js
    
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
