name: Test JS build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        haxe: [4.3.3]
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      # Checkout & install haxe
      - uses: actions/checkout@v2

      # - name: Restore cached haxe installation
      #   id: cache-primes-restore
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: |
      #       path/to/dependencies
      #       some/other/dependencies
      #     key: ${{ runner.os }}-primes
      
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version
      - run: which haxe

      # Install libs
      - run: haxe setup.hxml
      - run: haxelib list

      # Try to build
      - run: haxe build.js.hxml

